version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: lubern5/vprofiledb
    container_name: vprodb
    ports:
      - "8000:5000"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="12345"
  
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
    
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      
  vproapp:
    build:
      context: ./Docker-files/app
    image: lubern5/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: lubern5/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}